In [2]:
import pandas as pd
df = pd.read_csv("sales.csv")

df.head()

   order_id   product     category  amount
0         1     Mouse  Electronics   31154
1         2  Keyboard  Electronics   15708
2         3  Keyboard  Electronics   21960
3         4  Keyboard  Electronics   19886
4         5  Keyboard  Electronics   43910

In [3]:
from google.colab import files

uploaded = files.upload()

Saving sales.csv to sales (1).csv

import pandas as pd

df = pd.read_csv("sales.csv")

df.head()

In [6]:
df.loc[10, "amount"] = None
df.loc[20, "amount"] = None

In [7]:
df.isnull().sum()

order_id    0
product     0
category    0
amount      2
dtype: int64

In [8]:
df["amount"] = df["amount"].fillna(0)

In [9]:
df.isnull().sum()

order_id    0
product     0
category    0
amount      0
dtype: int64

In [10]:
df.to_csv("sales_cleaned.csv", index=False)

In [4]:
import pandas as pd

df = pd.read_csv("sales.csv")

df.head()

   order_id   product     category  amount
0         1     Mouse  Electronics   31154
1         2  Keyboard  Electronics   15708
2         3  Keyboard  Electronics   21960
3         4  Keyboard  Electronics   19886
4         5  Keyboard  Electronics   43910

In [11]:
from google.colab import files

files.download("sales_cleaned.csv")

In [5]:
import pandas as pd

df = pd.read_csv("sales.csv")

print(df.shape)

(1000, 4)